// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

// Search
export const CHANGE_METRO_LINE = 'CHANGE_METRO_LINE'
export const CHANGE_METRO_STATION = 'CHANGE_METRO_STATION'
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT'
export const METRO_FETCH_REQUESTED = 'METRO_FETCH_REQUESTED'
export const METRO_FETCH_SUCCEEDED = 'METRO_FETCH_SUCCEEDED'
export const METRO_FETCH_FAILED = 'METRO_FETCH_FAILED'
